### PR TITLE
Use --platform wasi/wasm instead of annotations

### PR DESCRIPTION
**Pull request by hydai**

### CODE REVIEW

**Comment by juntao** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/). Here are my reviews of code commits in this PR.

------

### [Commit 6f2887192cc570aba490158a60814bf3b4282922](https://github.com/WasmEdge/WasmEdge/pull/34/commits/6f2887192cc570aba490158a60814bf3b4282922)
The patch recommends using `--platform wasi/wasm` instead of annotations to run Wasm applications in containerd. The `container_annotations` and `pod_annotations` have been updated and references to `module.wasm.image/variant` have been removed. The `http_server_application.sh`, `simple_wasi_application.sh`, and related files have been updated to use `--platform` flag instead of annotations. The WasmEdge example applications have also been updated accordingly.
 
Potential problems: 
- It is unclear if any issues could arise from the removal of `module.wasm.image/variant` annotations without testing.
- It is unclear if this change will work with other runtimes or only with crun.
- No explanation is provided as to why `--platform wasi/wasm` is better than using annotations, or if this change has any performance improvements.

**Comment by alabulei1** [comment]
Hi  @hydai,
 
When can we merge this PR?

**Comment by hydai** [comment]
The CI failed. It needs to figure it out before getting merged.

**Comment by hydai** [comment]
This is outdated. Closing it.

**Pull request closed without merging**
