### PR TITLE
Refactor the workflow for handling different version pairs of wasmedge, crun, and zh-mirror.

### PR DESCRIPTION
**Pull request by hydai**
Signed-off-by: hydai <z54981220@gmail.com>

### CODE REVIEW

**Comment by juntao** [comment]
While the CI status shows success, if you look into the logs, most of them actually failed. 😥

**Comment by juntao** [comment]
cc @JcJinChen

**Comment by hydai** [comment]
> While the CI status shows success, if you look into the logs, most of them actually failed. 😥

Yes, I found that. Still investigating this problem.

**Comment by hydai** [comment]
The current status:

截圖 2022-07-27 at 06 25 01@2x


Also, I refactor the CI workflow to make it more clean and easy to maintain.

**Comment by hydai** [comment]
This is still a draft. Investigating the problem of the HTTP server example.

**Comment by juntao** [comment]
Thanks @hydai 

This is very helpful.

**Comment by hydai** [comment]
@juntao I am going to merge this first.
And will have another PR for fixing the HTTP server example with WasmEdge 0.10.0 and crun 1.5.

**Review by juntao — APPROVED** [review]
LGTM

**Pull request merged**
