### PR TITLE
modify the configuration about crio.image

### PR DESCRIPTION
**Pull request by JcJinChen**

### CODE REVIEW

**Comment by juntao** [comment]
Thanks! Can we have separate 

`crio/install.sh`
`crio/install-zh.sh`

as well? 

Then, perhaps we can have separate CIs for the zh versions of containerd and crio. Thanks!

**Comment by JcJinChen** [comment]
> Thanks! Can we have separate
> 
> `crio/install.sh` `crio/install-zh.sh`
> 
> as well?
> 
> Then, perhaps we can have separate CIs for the zh versions of containerd and crio. Thanks!

Of course. I will submit it again when i'm done.

**Comment by juntao** [comment]
Great. Mark this PR as draft please. When it is ready, we will review and merge. Thanks.

**Comment by JcJinChen** [comment]
> Great. Mark this PR as draft please. When it is ready, we will review and merge. Thanks.

Yeaph, I have separated CI for the zh versions of crio as well. Could you approve the github action for me?Thanks.

**Pull request merged**
