### PR TITLE
Enable more pairs of wasmedge + crun

### PR DESCRIPTION
**Pull request by hydai**
This is for figuring out all of the possible pair between wasmedge and crun, don't merge it unless I remove the WIP tag.

### CODE REVIEW

**Comment by hydai** [comment]
Ready to review

**Comment by juntao** [comment]
The rules are based on exclusions. Does that mean we will need to add a new set of exclusion rules for every new release of crun and WasmEdge? Can we create a crun and WasmEdge compatibility matrix? Thanks.

**Comment by hydai** [comment]
This is a temporary matrix, so we can quickly know the status of the compatibility matrix.
Since there is an upstream issue that will make the wasm execution flow fail (crun 1.7.1 and 1.7.2), that's why we will have an exclusions list. And the bugfix doesn't have a release. So we have to use the upstream main branch for the testing.

Should we simplify the table? For example, just skip the crun version `1.7.1` and `1.7.2`.

**Comment by hydai** [comment]
Remove the following versions for simplifying the matrix:
1. crun 1.5
2. wasmedge < 0.11.0

**Comment by hydai** [comment]
Once the upstream releases a new version, then we can also remove the remaining exclusive list.

**Comment by juntao** [comment]
I would like to support crun versions included in Fedora 37+ and EPEL 8 and 9.

**Comment by hydai** [comment]
> I would like to support crun versions included in Fedora 37+ and EPEL 8 and 9.

Then, we can focus on crun >= 1.7.

**Comment by hydai** [comment]
Hmmmm. I am wrong, it should be 1.6 on Fedora 37, and 1.7.x on Fedora 38
https://packages.fedoraproject.org/pkgs/crun/crun/

**Review by dm4 — APPROVED** [review]
LGTM

**Pull request merged**
